### ISSUE TITLE
Video play not working

### ISSUE THREAD

**Issue by Gdanycz** [web-hype/voductivity-for-brackets#2]
When I put a video or iframe from YT in my queue and load, it changes the background brackets, but nothing else happens, the video doesn't start playing :(

**Comment by micjohansson** [comment]
Hi @Gdanycz ,
Thanks for using Voductivity :)

Adding YT videos using URLs appears not to work because they set the "X-Frame-Options" header to "SAMEORIGIN", so it not allowed.

That said, I haven't be able to reproduce your issue when using the embed code. Please ensure the "Embed" option is selected when you add the iframe code.

If you can point me to a specific video you're having trouble with, I can look into it further.

**Comment by Gdanycz** [comment]
> Hi @Gdanycz , Thanks for using Voductivity :)
> 
> Adding YT videos using URLs appears not to work because they set the "X-Frame-Options" header to "SAMEORIGIN", so it not allowed.
> 
> That said, I haven't be able to reproduce your issue when using the embed code. Please ensure the "Embed" option is selected when you add the iframe code.
> 
> If you can point me to a specific video you're having trouble with, I can look into it further.

I tried a completely random video I had on YT, but no video works. https://youtu.be/kb9sjmA7RMA

**Comment by micjohansson** [comment]
I'm afraid I still can't reproduce it... Are you pressing "Load" once you add it? It should show a green "Loaded" button when it's ready.
<img width="1152" alt="Screenshot 2023-07-06 at 23 39 18" src="https://github.com/web-hype/voductivity-for-brackets/assets/40596630/d681244e-c6a3-4d47-a621-f8851a8c4810">

If you're still having a problem, could you please provide full steps to reproduce along with your IDE and OS versions.

**Comment by Gdanycz** [comment]
> I'm afraid I still can't reproduce it... Are you pressing "Load" once you add it? It should show a green "Loaded" button when it's ready. <img alt="Screenshot 2023-07-06 at 23 39 18" width="1152" src="https://user-images.githubusercontent.com/40596630/251589970-d681244e-c6a3-4d47-a621-f8851a8c4810.png">
> 
> If you're still having a problem, could you please provide full steps to reproduce along with your IDE and OS versions.

![image](https://github.com/web-hype/voductivity-for-brackets/assets/60316826/aaaaeee1-a70d-4fdf-97c2-9c42b2735f64)
![image](https://github.com/web-hype/voductivity-for-brackets/assets/60316826/06e951f9-d7f1-4077-86ce-7b6eda17bd39)

![image](https://github.com/web-hype/voductivity-for-brackets/assets/60316826/2c6f5eaa-55b6-473e-acf2-8e1d1a620499)
![image](https://github.com/web-hype/voductivity-for-brackets/assets/60316826/52e6931e-52c2-4759-8a76-71834899d984)

**Comment by micjohansson** [comment]
Thanks,
"Video" should be for local files... My bad for not making that clear.
For a link you'd need to have "URL" selected, but as mentioned previously that won't work for YouTube.

For YT videos you need to:
- Open the video in a browser
- Right-click on the video and select "Copy embed code" (or select "Share" -> "Embed" and copy the code)
- Back in VODuctivity, select "Embed" and paste the copied code into the "Link/Code" textbox.

Then you should be able to see the video when loaded.

**Comment by Gdanycz** [comment]
> Thanks, "Video" should be for local files... My bad for not making that clear. For a link you'd need to have "URL" selected, but as mentioned previously that won't work for YouTube.
> 
> For YT videos you need to:
> 
> * Open the video in a browser
> * Right-click on the video and select "Copy embed code" (or select "Share" -> "Embed" and copy the code)
> * Back in VODuctivity, select "Embed" and paste the copied code into the "Link/Code" textbox.
> 
> Then you should be able to see the video when loaded.


Thanks, it already works, how can I put the video over the whole IDE, I have it like this:
![image](https://github.com/web-hype/voductivity-for-brackets/assets/60316826/6f77d79b-e5cd-4157-9461-20efb8b60410)

And I have one more question, how can I play the local video, there I have to put the normal path directly to the video file?
